"""CLI for MDL/NLL scoring.

Computes MDL for code generated by the SLA agents and writes
``mdl_results.json`` (per app/task) + ``mdl_summary.json`` (aggregate)
under each backup's ``eval_results/`` tree.

Three scoring methods:

- ``dep_aware`` (default): MDL = NLL(lib) + Σ NLL(file | direct_deps).
  See ``el-agent/src/utils/mdl/scoring.py``.
- ``concat`` (legacy): MDL = NLL(lib) + Σ NLL(file | full_lib_prefix).
  See ``el-agent/src/utils/mdl/concat.py``.
- ``shared_concat``: MDL = NLL(cat(lib)) + Σ_app NLL(cat(app) | cat(lib)).
  Lib counted once across all apps in a suite. App-internal files see each
  other (sibling driver compression). See
  ``el-agent/src/utils/mdl/shared_concat.py``.

Two task modes (``--task``), each with its own backup layout:

- ``webgen``     React/JS, optional ui-lib. Legacy "loose" or unified layout.
- ``paperbench`` Python, unified layout:
                 ``backups/<bench>/<tag>/final/round_<N>/<phase>/tasks/<tid>/``.

Examples
--------

::

    # Webgen, explicit dirs
    python scripts/metrics/get_mdl.py \\
        --app_root_dir backups/poc-oracle-ver7-t1/final/apps \\
        --lib_dir       backups/poc-oracle-ver7-t1/final/ui-lib

    # Webgen, unified backup tag
    python scripts/metrics/get_mdl.py --task webgen \\
        --backup-tag sla-ours-v3-t1 --phase apply --round 4

    # Paperbench (unified layout — --phase required, --round defaults to latest)
    python scripts/metrics/get_mdl.py --task paperbench \\
        --backup-tag pb-rl-baseline-t1 --phase baseline --round 1 \\
        --paper-ids fre,rice

    # Legacy concat method
    python scripts/metrics/get_mdl.py --task webgen --method concat \\
        --backup-tag sla-ours-v3-t1 --phase apply --round 4

See ``el-agent/src/utils/mdl/README.md`` for the formula and JSON schema.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from dataclasses import dataclass, field
from typing import Awaitable, Callable

from dotenv import load_dotenv

_agent_src = os.path.join(os.path.dirname(__file__), "..", "..", "el-agent", "src")
if _agent_src not in sys.path:
    sys.path.insert(0, os.path.abspath(_agent_src))

from utils.mdl import (  # noqa: E402
    AppMDLResult,
    MDLMetric,
    TaskConfig,
    is_valid_codebase,
    load_task_config,
)
from utils.mdl.concat import score_concat  # noqa: E402
from utils.mdl.shared_concat import score_shared_concat  # noqa: E402
from run.backup_layout import (  # noqa: E402
    backup_eval_phase_dir,
    backup_final_phase_dir,
    extract_lib_dir_in_backup,
    latest_round_in_backup,
    task_dir_in_backup,
)


PROJECT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


# ----------------------------------------------------------------------
# Entry / cache
# ----------------------------------------------------------------------

@dataclass
class Entry:
    """One scoreable item (paper / task / webgen app)."""
    label: str
    app_dir: str
    lib_dir: str | None
    save_dir: str | None


@dataclass
class ResolveResult:
    """Returned by each per-task resolver."""
    entries: list[Entry]
    eval_root: str | None = None  # directory for the aggregate summary
    header_lines: list[str] = field(default_factory=list)


class LibNllCache:
    """Caches lib NLL per lib_dir within one CLI run.

    Replaces the pre-refactor pattern of stuffing ``_precomputed_lib`` into
    entry dicts. ``get(lib_dir)`` returns ``(library_nll, library_tokens)``
    suitable for ``MDLMetric.ascore(precomputed_lib=...)``.
    """

    def __init__(self, metric: MDLMetric, task: TaskConfig, *, strip_comments: bool):
        self._metric = metric
        self._task = task
        self._strip_comments = strip_comments
        self._cache: dict[str, tuple[float, int]] = {}

    async def get(self, lib_dir: str | None) -> tuple[float, int] | None:
        if not lib_dir:
            return None
        if lib_dir not in self._cache:
            parser = self._task.parser_module
            strip_fn = parser.strip_comments if self._strip_comments else None
            self._cache[lib_dir] = await self._metric._score_library(
                lib_dir, self._task, strip_fn,
            )
            nll, toks = self._cache[lib_dir]
            print(
                f"Library NLL: {nll:.1f} ({toks} tokens) "
                f"[{lib_dir}]"
                f"{' [comments stripped]' if self._strip_comments else ''}"
            )
        return self._cache[lib_dir]


# ----------------------------------------------------------------------
# Resolvers (one per task family) — pure path logic, no I/O on apps
# ----------------------------------------------------------------------

def _require(cond: bool, msg: str) -> None:
    if not cond:
        raise SystemExit(msg)


def _split_ids(value: str | None) -> list[str] | None:
    return [s.strip() for s in value.split(",") if s.strip()] if value else None


def resolve_unified(args: argparse.Namespace, *, bench: str) -> ResolveResult:
    """Unified backup layout (paperbench / webgen with backup-tag).

    Layout: ``backups/<bench>/<tag>/final/round_<N>/<phase>/tasks/<id>/``
    with ``submission/`` (always) + ``lib/`` (coding|apply) or
    phase-level ``round_<N>/extract/lib/`` (extract).
    """
    _require(bool(args.backup_tag), f"--task {bench} requires --backup-tag.")
    _require(not args.app_root_dir,
             f"--task {bench} cannot be combined with --app_root_dir.")
    _require(bool(args.phase),
             f"--task {bench} requires --phase <baseline|coding|apply|extract>.")
    _require(args.phase in ("baseline", "coding", "apply", "extract"),
             f"--phase must be one of baseline|coding|apply|extract (got {args.phase!r}).")

    round_n = args.round
    if round_n is None:
        round_n = latest_round_in_backup(PROJECT_DIR, bench, args.backup_tag, args.phase)
        _require(round_n is not None,
                 f"No round_N/{args.phase} found under "
                 f"backups/{bench}/{args.backup_tag}/final/. Pass --round explicitly.")

    final_phase = backup_final_phase_dir(PROJECT_DIR, bench, args.backup_tag, round_n, args.phase)
    eval_phase = backup_eval_phase_dir(PROJECT_DIR, bench, args.backup_tag, round_n, args.phase)
    tasks_dir = os.path.join(final_phase, "tasks")
    _require(os.path.isdir(tasks_dir), f"tasks/ not found under {final_phase}")

    tids = _split_ids(args.task_ids)
    if tids is None:
        tids = sorted(d for d in os.listdir(tasks_dir)
                      if os.path.isdir(os.path.join(tasks_dir, d)))

    # Phase-level lib (extract only)
    extract_lib = None
    if args.phase == "extract" and args.lib_dir is None:
        extract_lib = extract_lib_dir_in_backup(PROJECT_DIR, bench, args.backup_tag, round_n)
        if not os.path.isdir(extract_lib):
            print(f"[warn] extract phase lib not found at {extract_lib}; "
                  "scoring without library context.")
            extract_lib = None

    entries: list[Entry] = []
    for tid in tids:
        tdir = task_dir_in_backup(PROJECT_DIR, bench, args.backup_tag, round_n, args.phase, tid)
        submission = os.path.join(tdir, "submission")
        if not os.path.isdir(submission):
            print(f"[skip] {tid}: no submission dir at {submission}")
            continue
        lib_dir = args.lib_dir
        if lib_dir is None:
            if args.phase in ("coding", "apply"):
                per_task_lib = os.path.join(tdir, "lib")
                if os.path.isdir(per_task_lib):
                    lib_dir = per_task_lib
            elif args.phase == "extract":
                lib_dir = extract_lib
        entries.append(Entry(
            label=tid,
            app_dir=submission,
            lib_dir=lib_dir,
            save_dir=os.path.join(eval_phase, "tasks", tid),
        ))

    header = [
        f"[Config] bench={bench} tag={args.backup_tag} round={round_n} phase={args.phase}",
        f"[Config] final_phase={final_phase}",
        f"[Config] eval_phase={eval_phase}",
    ]
    return ResolveResult(entries, eval_phase, header)


def resolve_webgen_legacy(args: argparse.Namespace, task: TaskConfig) -> ResolveResult:
    """Webgen with explicit --app_root_dir (legacy path, one combined output)."""
    _require(bool(args.app_root_dir),
             "--task webgen requires either --app_root_dir or --backup-tag.")

    app_ids = set(_split_ids(args.app_ids) or [])
    entries: list[Entry] = []
    for app in sorted(os.listdir(args.app_root_dir)):
        app_dir = os.path.join(args.app_root_dir, app)
        if not is_valid_codebase(app_dir, task=task):
            continue
        if app_ids and app not in app_ids:
            continue
        entries.append(Entry(
            label=app,
            app_dir=app_dir,
            lib_dir=args.lib_dir,
            save_dir=None,  # webgen-legacy aggregates everything to one file
        ))
    return ResolveResult(entries, eval_root=None)


def resolve(args: argparse.Namespace, task: TaskConfig) -> ResolveResult:
    """Dispatch to the right resolver for the requested task."""
    if args.task == "webgen":
        if args.backup_tag:
            return resolve_unified(args, bench=args.bench or "webgen")
        return resolve_webgen_legacy(args, task)
    # paperbench: `resolve_unified` keys off args.task_ids — translate from
    # --paper-ids so paperbench-flavored invocations still work.
    if args.paper_ids and not args.task_ids:
        args.task_ids = args.paper_ids
    return resolve_unified(args, bench=args.bench or "paperbench")


# ----------------------------------------------------------------------
# Scoring loop
# ----------------------------------------------------------------------

ScoreFn = Callable[[MDLMetric, Entry, TaskConfig, LibNllCache, bool], Awaitable[AppMDLResult]]


async def _score_entry_dep_aware(
    metric: MDLMetric, entry: Entry, task: TaskConfig,
    cache: LibNllCache, strip_comments: bool,
) -> AppMDLResult:
    precomp = await cache.get(entry.lib_dir)
    return await metric.ascore(
        entry.app_dir, entry.lib_dir,
        task=task, precomputed_lib=precomp,
        strip_comments=strip_comments,
    )


async def _score_entry_concat(
    metric: MDLMetric, entry: Entry, task: TaskConfig,
    cache: LibNllCache, strip_comments: bool,
) -> AppMDLResult:
    precomp = await cache.get(entry.lib_dir)
    return await score_concat(
        metric, entry.app_dir, entry.lib_dir,
        task=task, strip_comments=strip_comments, precomputed_lib=precomp,
    )


METHOD_SCORERS: dict[str, ScoreFn] = {
    "dep_aware": _score_entry_dep_aware,
    "concat":    _score_entry_concat,
}


async def _run_shared_concat(
    metric: MDLMetric,
    entries: list[Entry],
    task: TaskConfig,
    strip_comments: bool,
    verbose: bool,
) -> list[tuple[Entry, dict]]:
    """Group entries by lib_dir, run one ``score_shared_concat`` per group.

    Lib NLL is measured once per unique lib_dir and re-attached identically to
    every app record in the group. ``_summarize_shared`` counts it once.
    """
    groups: dict[str, list[Entry]] = {}
    order: list[str] = []
    for e in entries:
        key = os.path.abspath(e.lib_dir) if e.lib_dir else "__no_lib__"
        if key not in groups:
            groups[key] = []
            order.append(key)
        groups[key].append(e)

    out: list[tuple[Entry, dict]] = []
    lib_cache: dict[str, tuple[float, int, str]] = {}
    for key in order:
        group = groups[key]
        lib_dir = group[0].lib_dir
        app_dirs = [(e.label, e.app_dir) for e in group]
        precomp = lib_cache.get(key)
        print(f"Getting shared-concat MDL for {len(group)} app(s) sharing lib={lib_dir or '(none)'}")
        suite = await score_shared_concat(
            metric, app_dirs, lib_dir,
            task=task, strip_comments=strip_comments,
            precomputed_lib=precomp,
        )
        lib_cache[key] = (suite.library_nll, suite.library_tokens, suite.lib_text_hash)
        print(f"  lib_nll={suite.library_nll:.1f} ({suite.library_tokens} tokens) "
              f"hash={suite.lib_text_hash[:8]}")
        for entry, result in zip(group, suite.app_results):
            out.append((entry, result.as_dict()))
            if verbose:
                _print_verbose(result, "shared_concat")
    return out


def _print_verbose(result: AppMDLResult, method: str) -> None:
    has_deps = method == "dep_aware"
    header = f"  {'File':<35s} {'NLL':>8s} {'Tokens':>7s} {'NLL/tok':>8s}"
    if has_deps:
        header += "  Deps"
    print(header)
    for fd in result.file_details:
        line = f"  {fd.rel_path:<35s} {fd.nll:>8.1f} {fd.tokens:>7d} {fd.nll_per_token:>8.3f}"
        if has_deps:
            deps_str = ", ".join(os.path.basename(p) for p in fd.dep_paths) if fd.dep_paths else "(none)"
            line += f"  {deps_str}"
        print(line)
    npt = result.app_nll / result.app_tokens if result.app_tokens > 0 else float("nan")
    print(f"  {'TOTAL':<35s} {result.app_nll:>8.1f} {result.app_tokens:>7d} {npt:>8.3f}")
    print()


# ----------------------------------------------------------------------
# Aggregation + JSON output
# ----------------------------------------------------------------------

def _summarize(results: list[dict]) -> dict:
    if not results:
        return {"sum_app_nll": 0.0, "avg_library_nll": 0.0, "mdl_nll": 0.0, "total_apps": 0}
    total_app_nll = sum(float(r.get("app_nll", 0.0)) for r in results)
    avg_lib_nll = sum(float(r.get("library_nll", 0.0)) for r in results) / len(results)
    return {
        "sum_app_nll": round(total_app_nll, 4),
        "avg_library_nll": round(avg_lib_nll, 4),
        "mdl_nll": round(total_app_nll + avg_lib_nll, 4),
        "total_apps": len(results),
    }


def _summarize_shared(results: list[dict]) -> dict:
    """Lib counted once (not averaged). All records carry identical library_nll
    within a single suite — pick the first one. For per-task files (one record
    each), this collapses to the same value."""
    if not results:
        return {
            "library_nll": 0.0, "library_tokens": 0,
            "sum_app_nll": 0.0, "sum_app_tokens": 0,
            "mdl_nll": 0.0, "total_tokens": 0,
            "nll_per_token": 0.0, "total_apps": 0,
        }
    lib_nll = float(results[0].get("library_nll", 0.0))
    lib_tokens = int(results[0].get("library_tokens", 0))
    sum_app_nll = sum(float(r.get("app_nll", 0.0)) for r in results)
    sum_app_tokens = sum(int(r.get("app_tokens", 0)) for r in results)
    total_nll = lib_nll + sum_app_nll
    total_tokens = lib_tokens + sum_app_tokens
    return {
        "library_nll": round(lib_nll, 4),
        "library_tokens": lib_tokens,
        "sum_app_nll": round(sum_app_nll, 4),
        "sum_app_tokens": sum_app_tokens,
        "mdl_nll": round(total_nll, 4),
        "total_tokens": total_tokens,
        "nll_per_token": round(total_nll / total_tokens, 4) if total_tokens else 0.0,
        "total_apps": len(results),
    }


FNAME_BY_METHOD = {
    "dep_aware":     ("mdl_results.json",        "mdl_summary.json"),
    "concat":        ("mdl_results_old.json",    "mdl_summary_old.json"),
    "shared_concat": ("mdl_results_shared.json", "mdl_summary_shared.json"),
}


def _summarize_for_method(method: str, results: list[dict]) -> dict:
    if method == "shared_concat":
        return _summarize_shared(results)
    return _summarize(results)


def _write_outputs(
    *, task: str, method: str,
    records: list[tuple[Entry, dict]],
    eval_root: str | None, webgen_legacy_save_dir: str | None,
) -> None:
    fname, summary_fname = FNAME_BY_METHOD[method]

    # Per-entry files (paperbench + webgen-unified)
    per_entry_layout = (
        task == "paperbench"
        or (task == "webgen" and eval_root is not None)
    )
    if per_entry_layout:
        for entry, rec in records:
            sd = entry.save_dir
            if sd is None:
                continue
            os.makedirs(sd, exist_ok=True)
            payload = {"apps": [rec], "summary": _summarize_for_method(method, [rec])}
            out_path = os.path.join(sd, fname)
            with open(out_path, "w", encoding="utf-8") as f:
                json.dump(payload, f, indent=2, ensure_ascii=False)
            print(f"Saved to: {out_path}")
        if eval_root and records:
            os.makedirs(eval_root, exist_ok=True)
            agg = {
                "apps": [rec for _, rec in records],
                "summary": _summarize_for_method(method, [rec for _, rec in records]),
            }
            agg_path = os.path.join(eval_root, summary_fname)
            with open(agg_path, "w", encoding="utf-8") as f:
                json.dump(agg, f, indent=2, ensure_ascii=False)
            print(f"Aggregated to: {agg_path}")
        return

    # Webgen-legacy: one combined file
    payload = {
        "apps": [rec for _, rec in records],
        "summary": _summarize_for_method(method, [rec for _, rec in records]),
    }
    if webgen_legacy_save_dir:
        os.makedirs(webgen_legacy_save_dir, exist_ok=True)
        out_path = os.path.join(webgen_legacy_save_dir, fname)
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)
        print(f"Saved to: {out_path}")
    else:
        print(json.dumps(payload, ensure_ascii=False, indent=2))


# ----------------------------------------------------------------------
# Entry point
# ----------------------------------------------------------------------

async def run(args: argparse.Namespace) -> None:
    task = load_task_config(args.task)
    resolved = resolve(args, task)

    for line in resolved.header_lines:
        print(line)
    if not resolved.entries:
        print("[info] no entries to score.")
        return

    metric = MDLMetric(
        model=args.model,
        base_url=args.openai_base_url,
        api_key=args.openai_api_key,
        joiner=args.joiner,
        max_concurrency=args.max_concurrency,
    )
    if args.method == "shared_concat":
        records = await _run_shared_concat(
            metric, resolved.entries, task, args.strip_comments, args.verbose,
        )
    else:
        cache = LibNllCache(metric, task, strip_comments=args.strip_comments)
        score_one = METHOD_SCORERS[args.method]
        records: list[tuple[Entry, dict]] = []
        for entry in resolved.entries:
            label_method = "dep-aware" if args.method == "dep_aware" else "concat"
            print(f"Getting {label_method} MDL for {entry.label}")
            result = await score_one(metric, entry, task, cache, args.strip_comments)
            records.append((entry, result.as_dict()))
            if args.verbose:
                _print_verbose(result, args.method)

    _write_outputs(
        task=args.task, method=args.method, records=records,
        eval_root=resolved.eval_root, webgen_legacy_save_dir=args.save_dir,
    )


def main() -> None:
    load_dotenv(os.path.join(PROJECT_DIR, ".env"))

    p = argparse.ArgumentParser(description="MDL/NLL metric (dep-aware or concat).")
    p.add_argument("--task", default="webgen",
                   choices=["webgen", "paperbench"])
    p.add_argument("--bench", default=None,
                   help="Backup root override under backups/ (default: same "
                        "as --task; e.g. webgen-maint for maintenance runs).")

    # Webgen-legacy explicit dirs
    p.add_argument("--app_root_dir", default=None,
                   help="[webgen-legacy] App-root dir (subdir per app).")
    p.add_argument("--lib_dir", default=None,
                   help="Override library dir. For paperbench/webgen-unified, "
                        "this overrides the auto-detected per-task lib.")
    p.add_argument("--app-ids", default=None, dest="app_ids",
                   help="[webgen-legacy] Comma-separated app IDs.")

    # Backup-tag based modes
    p.add_argument("--backup-tag", default=None, dest="backup_tag")
    p.add_argument("--paper-ids", default=None, dest="paper_ids",
                   help="[paperbench] Comma-separated paper IDs.")
    p.add_argument("--task-ids", default=None, dest="task_ids",
                   help="[paperbench/webgen-unified] Comma-separated task IDs.")
    p.add_argument("--round", default=None, type=int, dest="round",
                   help="[unified] round_<N>. Default: latest having --phase on disk.")
    p.add_argument("--phase", default=None,
                   help="[unified] baseline|coding|apply|extract.")

    # Scoring
    p.add_argument("--method", default="dep_aware",
                   choices=["dep_aware", "concat", "shared_concat"])
    p.add_argument("--model", default="Qwen/Qwen2.5-7B")
    p.add_argument("--joiner", default="\n")
    p.add_argument("--max_concurrency", type=int, default=1)
    p.add_argument("--openai_base_url",
                   default=os.environ.get("MDL_BASE_URL", "http://127.0.0.1:8000/v1"),
                   help="vLLM endpoint; defaults to the server deploy_vllm.sh starts locally. "
                        "Also settable via MDL_BASE_URL.")
    p.add_argument("--openai_api_key", default="EMPTY")

    p.add_argument("--save_dir", default=None,
                   help="[webgen-legacy] Output dir; ignored for backup-tag modes.")
    p.add_argument("--verbose", action="store_true")
    p.add_argument("--no-strip-comments", action="store_true",
                   help="Disable comment stripping (default: stripped).")

    args = p.parse_args()
    if isinstance(args.lib_dir, str) and args.lib_dir.strip().lower() in {"none", "null", ""}:
        args.lib_dir = None
    args.strip_comments = not args.no_strip_comments

    asyncio.run(run(args))


if __name__ == "__main__":
    main()
